version: "3"
services:
  database:
    image: mdillon/postgis:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mix phx.server
    ports:
      - 5000:5000
    volumes:
      - build:/app/_build
      - deps:/app/deps
      - ./apps:/app/apps/
    env_file:
        - .env
    depends_on:
        - database
volumes:
  pgdata:
  .:
  build:
  .:
  deps:
  .:
